/*  TRAE LA CANTIDAD DE JEFES DE DEPARTAMENTO POR CADA DEPARTAMENTO.
    TAMBIEN SE PUEDE FILTRAR POR UN DEPARTAMENTO EN ESPECIFICO.
    COMO NO EXISTE EL ILIKE (CASE INSENSITIVE) EN MYSQL SE USA UPPER O LOWER. */

SELECT
    COUNT(*) AS CANTIDAD_JEFES,
    D.DEPT_NAME AS DEPARTAMENTO

FROM dept_manager AS DM

JOIN departments as D ON D.DEPT_NO = DM.DEPT_NO

/*  ESTE O EL DE ABAJO. */
WHERE UPPER(D.DEPT_NAME) like 'PROD%'
-- WHERE LOWER(D.DEPT_NAME) like 'prod%'


GROUP BY D.DEPT_NAME

ORDER BY D.DEPT_NAME;
